gui:
  theme:
    activeBorderColor:
      - "#89b4fa"  # blue
      - bold
    inactiveBorderColor:
      - "#585b70"  # grey
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    selectedRangeBgColor:
      - "#45475a"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#f38ba8"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

git:
  paging:
    colorArg: always
    pager: delta --paging=never --features=tokyonight

