# install starship to begin using
# install with shell
# curl -sS https://starship.rs/install.sh | sh

# if in macos, install with homebrew. 
# brew install starship

# configuration for bash
# ~/.bashrc
# eval "$(starship init bash)"

# configuration for zsh
# ~/.zshrc
# eval "$(starship init zsh)"

# configuration for fish
# ~/.config/fish/config.fish
# starship init fish | source


# can use your distro icon in place of  
format = """\
[](bg:#1e1e2e fg:#a6e3a1)\
[ ](bg:#a6e3a1 fg:#1e1e2e)\
[](fg:#a6e3a1 bg:#313244)\
$time\
[](fg:#313244 bg:#94e2d5)\
$directory\
$git_branch\
$git_status\
[](fg:#94e2d5 bg:#1e1e2e)\
$character\
"""

[time]
disabled = false
time_format = "%R"
style = "bg:#313244 fg:#89b4fa"
format = "[ 󱑍 $time ]($style)"

[directory]
format = "[  $path ]($style)"
style = "fg:#313244 bg:#94e2d5"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:#94e2d5 bg:#313244"
format = '[](fg:#94e2d5 bg:#313244)[ $symbol $branch ]($style)'

[git_status]
style = "bg:#a6e3a1 fg:#1e1e2e"
format = '[ $modified$staged$untracked$conflicted$ahead_behind ]($style)'

# Git status symbols
modified = '$count! '
staged = '$count󰱒 '
untracked = '$count '
conflicted = '$count '
ahead = '$count⇡ '
behind = '$count⇣ '
diverged = '$ahead_count⇕⇡ $behind_count⇣'

[character]
success_symbol = '[ ➜](fg:#a6e3a1 bold)'
error_symbol = '[ ✗](fg:#f38ba8 bold)'
